# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    api.repository.zone:
        class: ApiBundle\Repository\ZoneRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - ApiBundle\Entity\Zone
        lazy: true

    api.repository.zone_type:
        class: ApiBundle\Repository\ZoneTypeRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - ApiBundle\Entity\ZoneType
        lazy: true