<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ElectRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ElectRepository extends EntityRepository
{
}
