<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ZoneRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends EntityRepository
{
    public function findAllByType($type)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $queryBuilder
            ->select("*, ST_GeomFromGeoJSON(z.shapePolygon) as shape_polygon, ST_GeomFromGeoJSON(z.shapeMultipolygon) as shape_multipolygon")
            ->where("zoneType := type")
            ->setParameter('type', $type)
        ;

        return $queryBuilder->getQuery()->getResult();
    }
}
