<?php

namespace ApiBundle\Repository;

use ApiBundle\Entity\Zone;
use ApiBundle\Entity\ZoneType;
use Doctrine\ORM\EntityRepository;

/**
 * ZoneRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends EntityRepository
{

    /**
     * @param ZoneType $zoneType
     * @return array|Zone[]
     */
    public function getZonesByZoneType(ZoneType $zoneType):array
    {
        return $this->findBy(['type' => $zoneType]);
    }
}
